using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using OrderProcessing.Api.Contracts.V1;
using OrderProcessing.Api.Mapping;
using OrderProcessing.Application.Orders.Listing;
using OrderProcessing.Application.Orders.Payments;
using OrderProcessing.Application.Orders.Submit;
using OrderProcessing.Domain.Orders;

namespace OrderProcessing.Api.Controllers;

[Route("api/v{version:apiVersion}/orders")]
public sealed class OrdersController(
    SubmitOrderUseCase submitOrder,
    OrderPaymentProcessor paymentProcessor,
    GetUserOrdersUseCase getUserOrders) : ApiControllerBase
{
    /// <summary>Submits a new order and attempts payment.</summary>
    /// <remarks>
    /// Every submission needs an <c>Idempotency-Key</c> header so that a request can be retried safely, for example
    /// after a timeout.
    ///
    /// - Generate a new key (a UUID works well) for each order attempt and send the same key when retrying that
    ///   attempt. It is not the order number: the order number is generated by the server and only known from the
    ///   response.
    /// - The first request with a key creates the order and charges it.
    /// - Repeating the request with the same key and payload never creates another order or charge. It returns the
    ///   original outcome: the receipt, or the same <c>422</c> with the same <c>orderNumber</c>. To retry a declined
    ///   payment, call the resubmit endpoint rather than reusing the key.
    /// - Using the same key with a different payload returns <c>409</c>.
    /// - Keys are scoped to the <c>userId</c> in the payload.
    /// </remarks>
    /// <param name="request">The order to submit.</param>
    /// <param name="idempotencyKey">Client-generated key that identifies this order attempt, for example a UUID.
    /// Required, at most 255 characters, no blank value or control characters. Reuse it only to retry the same request.
    /// </param>
    /// <param name="ct">Cancellation token.</param>
    /// <response code="200">The order was paid, or it had already been paid: the receipt.</response>
    /// <response code="400">The request is invalid: a missing or invalid <c>Idempotency-Key</c>, missing fields, an amount of zero or less or with more than two decimal places, a description over 500 characters, an unknown gateway or an unsupported currency.</response>
    /// <response code="409">The <c>Idempotency-Key</c> was already used with a different payload.</response>
    /// <response code="422">The gateway declined the payment. The body contains the <c>orderNumber</c>, which can be resubmitted.</response>
    /// <response code="504">The gateway did not answer in time, so the payment may or may not have gone through. The order stays pending. Retry with the same <c>Idempotency-Key</c>. The body contains the <c>orderNumber</c>.</response>
    [HttpPost]
    [ProducesResponseType<OrderReceiptResponse>(StatusCodes.Status200OK)]
    [ProducesResponseType<OrderErrorResponse>(StatusCodes.Status422UnprocessableEntity)]
    [ProducesResponseType<ValidationProblemDetails>(StatusCodes.Status400BadRequest)]
    [ProducesResponseType<ProblemDetails>(StatusCodes.Status409Conflict)]
    [ProducesResponseType<ProblemDetails>(StatusCodes.Status504GatewayTimeout)]
    public async Task<IActionResult> Submit(
        SubmitOrderRequest request,
        [FromHeader(Name = ApiHeaders.IdempotencyKey), Required, MaxLength(IdempotencyKey.MaxLength)] string idempotencyKey,
        CancellationToken ct)
    {
        var command = request.ToCommand(new IdempotencyKey(idempotencyKey));
        return ToActionResult(await submitOrder.ExecuteAsync(command, ct));
    }

    /// <summary>Retries payment for an existing order. Paid orders return their existing receipt.</summary>
    /// <remarks>
    /// Safe to repeat: an order is never charged twice, and concurrent calls for the same order charge it once.
    /// Use this endpoint to retry a declined payment.
    /// </remarks>
    /// <param name="orderNumber">Number of the order to retry, as returned by the submit endpoint.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <response code="200">The order is paid: the receipt (the existing one if it was already paid).</response>
    /// <response code="404">There is no order with this number.</response>
    /// <response code="422">The gateway declined the payment again.</response>
    /// <response code="504">The gateway did not answer in time. The order stays pending and can be resubmitted again.</response>
    [HttpPost("{orderNumber}/resubmit")]
    [ProducesResponseType<OrderReceiptResponse>(StatusCodes.Status200OK)]
    [ProducesResponseType<OrderErrorResponse>(StatusCodes.Status422UnprocessableEntity)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType<ProblemDetails>(StatusCodes.Status504GatewayTimeout)]
    public async Task<IActionResult> Resubmit(string orderNumber, CancellationToken ct)
    {
        return ToActionResult(await paymentProcessor.ProcessAsync(new OrderNumber(orderNumber), ct));
    }

    /// <summary>Lists a user's orders, newest first.</summary>
    /// <param name="userId">Identifier of the user whose orders to list.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <response code="200">The user's orders, sorted by creation time, newest first. Empty if there are none.</response>
    /// <response code="400"><c>userId</c> is missing.</response>
    [HttpGet]
    [ProducesResponseType<IReadOnlyList<OrderSummaryResponse>>(StatusCodes.Status200OK)]
    [ProducesResponseType<ValidationProblemDetails>(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<IReadOnlyList<OrderSummaryResponse>>> List(
        [FromQuery, Required] string userId, CancellationToken ct)
    {
        var orders = await getUserOrders.ExecuteAsync(userId, ct);
        return Ok(orders.Select(o => o.ToResponse()).ToList());
    }

    private IActionResult ToActionResult(OrderProcessingResult result) => result switch
    {
        OrderProcessingResult.Paid paid => Ok(paid.Receipt.ToResponse()),
        OrderProcessingResult.AlreadyPaid alreadyPaid => Ok(alreadyPaid.Receipt.ToResponse()),
        OrderProcessingResult.Failed failed => UnprocessableEntity(failed.Error.ToResponse()),
        _ => throw new InvalidOperationException($"Unexpected result {result.GetType().Name}.")
    };
}
